# Generated by Django 3.2.18 on 2023-04-20 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20230420_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='select1_users',
            field=models.ManyToManyField(related_name='selects1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='select2_users',
            field=models.ManyToManyField(related_name='selects2', to=settings.AUTH_USER_MODEL),
        ),
    ]
